export const ALL_CHARACTERS = [
  'Astral Alpaca',
  'Basic Bird',
  'Blessed Beetle',
  'Bouncy Bunny',
  'Clumsy Chicken',
  'Confused Crab',
  'Cosmic Capybara',
  'Cursed Cat',
  'Derpy Dog',
  'Disco Duck',
  'Fancy Flamingo',
  'Fossil Fish',
  'Funky Frog',
  'Galaxy Goat',
  'Grumpy Cat',
  'Haunted Hamster',
  'Lazy Lizard',
  'Mysterious Mongoose',
  'Neon Narwhal',
  'Noble Newt',
  'Odd Octopus',
  'Odd Otter',
  'Peculiar Platypus',
  'Plain Penguin',
  'Primordial Pig',
  'Sacred Salamander',
  'Sleepy Sloth',
  'Sneaky Snail',
  'Spooky Spider',
  'Star Serpent',
  'THE ABSOLUTE UNIT',
  'THE INFINITE VOID',
  'The Eternal Egg',
  'Turbo Turkey',
  'Weird Weasel',
  'Wobble Worm',
  'Wobbly Walrus',
]
